subnet 10.0.0.0 netmask 255.255.252.0 {
    range 10.0.3.100 10.0.3.200;
    option subnet-mask 255.255.252.0;
    option routers 10.0.0.1;
    option domain-name-servers 10.0.0.2, 10.0.0.3, 9.9.9.9;
    default-lease-time 900;
    max-lease-time 3600;
}

# Raspberry Pi3 running PiHole
host dns {
  hardware ethernet b8:27:eb:c8:af:0e;
  fixed-address 10.0.0.2;
}
# Rack Mounted 24 port switch
host sw-tpl-24 {
  hardware ethernet C4:6E:1F:BF:73:58;
  fixed-address 10.0.0.10;
}
host ap-tpl-archer-a7 {
  hardware ethernet 0C:80:63:A0:54:01;
  fixed-address 10.0.0.11;
}
host ap-tpl-wa855re {
  hardware ethernet 0C:80:63:48:19:0C;
  fixed-address 10.0.0.12;
}
host ap-tpl-re300 {
  hardware ethernet E6:F1:CF:E7:F1:CF;
  fixed-address 10.0.0.13;
}
host bm-nas {
  hardware ethernet 50:E5:49:B9:DA:E0;
  fixed-address 10.0.0.20;
}
host bm-docker {
  hardware ethernet D0:50:99:32:96:E6;
  fixed-address 10.0.0.210;
}
host acer-proxmox {
  hardware ethernet C0:18:50:44:D2:02;
  fixed-address 10.0.1.1;
}
host vm-homeassistant {
  hardware ethernet 02:DE:81:79:B2:A2;
  fixed-address 10.0.1.130;
}
host vm-ansible {
  hardware ethernet BC:24:11:D1:5F:17;
  fixed-address 10.0.1.134;
}
host bm-beelink {
  hardware ethernet E8:FF:1E:D3:31:3F;
  fixed-address 10.0.0.21;
}
#host  {
#  hardware ethernet ;
#  fixed-address ;
#}
