#!/usr/sbin/nft -f

# Delete ALL Rules
flush ruleset

# Bogons - IPs that should never be a source IP
define BOGONS4 = { 0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 240.0.0.0/4, 255.255.255.255/32 }

# Define Interfaces
define WANLINK = eth1 # USB NIC
define LANLINK = eth0 # Rasberry Pi OnBoard NIC
# Define Ports for Port Forwarding
#define PORTFORWARDS = {http, https}

# Firewall
table inet filter {
        # Inbound from World
        chain inbound_world {
                # Deny BOGONS as defined above.
                ip saddr { $BOGONS4 } drop
        }

        # Inbound from Private
        chain inbound_private {
                # Allow SSH, DNS, DHCP
                ip protocol . th dport vmap { tcp . 22 : accept, udp . 53 : accept, tcp . 53 : accept, udp . 67 : accept }
        }

        # Inbound from ANY
        chain inbound {
                # Default DENY
                type filter hook input priority 0; policy drop;

                # Allow Established and Related connections -- Internal <-> External
                ct state vmap { established : accept, related : accept, invalid : drop} counter

                # ICMP Rules
                icmp type echo-request counter limit rate 5/second accept
                ip protocol icmp icmp type { destination-unreachable, echo-reply, echo-request, source-quench, time-exceeded } accept

                # Drop spoofed loopback traffic
                iifname "lo" ip daddr != 127.0.0.0/8 drop

                # Interface specific rules
                iifname vmap { lo: accept, $WANLINK : jump inbound_world, $LANLINK : jump inbound_private }
        }

        # Forwarding Rules
        chain forward {
                # Default DENY
                type filter hook forward priority 0; policy drop;

                # Allow Established and Related connections -- Internal <-> External
                ct state vmap { established : accept, related : accept, invalid : drop }

                # Let traffic from this router and from the Internal network get out onto the Internet
                iifname { lo, $LANLINK } accept

                # Port Forwarding to/from INTERNET
                #tcp dport { $PORTFORWARDS } counter
        }
}

# NAT
table ip nat {
        chain  prerouting {
                type nat hook prerouting priority -100;
                # Send specific inbound traffic to our internal web server (only relevant if we present services to the Internet).
                #iifname $WANLINK tcp dport { $PORTFORWARDS } dnat to 10.199.200.10
        }
        chain postrouting {
                type nat hook postrouting priority 100; policy accept;
                # Pretend that outbound traffic originates in this router so that Internet servers know where to send responses
                oif $WANLINK masquerade
        }
}
